### ISSUE TITLE
Deprecated implementation of CreateServiceRemotingListener

### ISSUE THREAD

**Issue by andrey-prokhorov** [aloneguid/pluralsight-azureservicefabric-programmingmodels#1]
I tried to follow along with the course and got a newer version (v4.0) of the package "Microsoft.ServiceFabric.Services.Remoting.Runtime" where "CreateServiceRemotingListener" cannot be used anymore (deprecated implementation).

Fortunately for us another method could be used instead of "[CreateServiceRemotingListener](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.remoting.runtime.serviceremotingextensions.createserviceremotingreplicalisteners?view=azure-dotnet)" in: 

https://github.com/aloneguid/pluralsight-azureservicefabric-programmingmodels/blob/7993981ea5a90d378448465803741e6b22fcca3d/M3/ECommerce.ProductCatalog/ProductCatalog.cs#L47

Example from [stackoverflow](https://stackoverflow.com/a/46753002/2021224):

```
protected override IEnumerable<ServiceReplicaListener> CreateServiceReplicaListeners()
{
    return this.CreateServiceRemotingReplicaListeners();
}
```

**Comment by aloneguid** [comment]
Hi @andrey-prokhorov thanks for reporting this. It's not exactly deprecated, it's in V1 of SF Remoting which is not supported by .NET Core, only by .NET Framework services. We are in discussion at the moment with Pluralsight to update the whole course to latest API, including .NET Core samples. I'm really keen to do this!

**Comment by andrey-prokhorov** [comment]
Hi @aloneguid, all right! Good to know 😄

**Comment by aloneguid** [comment]
The updated course should be live in a few days, closing this for now ;)
